### ISSUE TITLE
Not using full area

### ISSUE THREAD

**Issue by arashbehmand** [tomoki1207/vscode-pdfviewer#10]
As you can see, there is always a white space at bottom and right of the pdf viewer. No matter if I resize the screen, it's always there. Also Toggling the side bar and panel doesn't affect the percent of white space (in other words the white space scales with the pdf viewer).
![capture](https://cloud.githubusercontent.com/assets/4283677/23749126/e635f278-04db-11e7-812d-edeaa9fc0881.PNG)

Thank you for this valuable plugin.

**Comment by tomoki1207** [comment]
@arashbehmand Thank you for reporting.
This behavior occurred with any PDF files?
And what is down-arrow icon at left bottom?

**Comment by arashbehmand** [comment]
thanks for your reply.
that down-arrow is for my download manager program, nothing that matters.
In order to reproduce this problem, I downloaded a portable version of vscode, and with my surprise found out that I don't have problem there. then I tried to add extensions that i had and apply my settings in the portable vscode.
After some effort, I Succeeded. It seems that this problem is because of my "zoom level". Try it your self increasing zoom level (`ctrl`+`+`) and decreasing zoom level (`ctrl`+`-`) make things out of order.

**Comment by tomoki1207** [comment]
@arashbehmand Thanks a lot for investigation.
I reproduced this issue by `ctrl`+`+` and `ctrl`+`-` in my VSCode.
It might difficult to fix it completely because the behaviors about change zoom-level are a little strange even previews by built-in markdown extension.
Anyway, I will investigate more.
BTW, `ctrl`+`mouse wheel` seems zoom-up/down without this problem. But affect to only text editor and reset zoom is not work. :(

**Comment by edasaki** [comment]
This is a problem in electron (base framework for vscode), it's been reported here

@electron/electron#7375

Still not fixed :(

**Comment by tomoki1207** [comment]
It looks like fixed.
