### ISSUE TITLE
Load On Restart

### ISSUE THREAD

**Issue by arrowj** [tomoki1207/vscode-pdfviewer#21]
Any way to have the pdf reload (to last page viewed) when reopening VSC?

**Comment by SJWackness** [comment]
If it could remember the last page/view that would be ideal. Even if it opened the file from page 1 upon restart VSC would be a huge help. I have PDFs open with lecture notes and saved workspaces, but when I reload VSC I have to manually re-open all of the PDFs from the previous state. The panels with the file name are as they were, but an error message is displayed instead of the PDF content.

**Comment by cooknl** [comment]
Same issue. Within a workspace, if I have a PDF viewed in a window, then shut down and reload VS Code, the PDF does not display.

**Comment by tomoki1207** [comment]
Close for aggregating.
If you want other features, please comment to the new issue.
