### ISSUE TITLE
Opens multiple pdf's of the same file when called

### ISSUE THREAD

**Issue by DaKeiser** [tomoki1207/vscode-pdfviewer#48]
#### Issue Type
Bug

#### Issue Description
While trying to open a particular pdf file multiple copies of that file open simultaneously.

#### Screenshot
![issue](https://user-images.githubusercontent.com/42712983/66218539-02c7e780-e6e7-11e9-98ef-b7d84417f8cd.gif)

**Comment by tomoki1207** [comment]
Because display flow is improved, these copies no longer opened probably.
But related to #57, preview is broken when open with new Code window (even when called from `code test.pdf`).
If you want to open by above command, open Code with no editor first.

So close this issue because main problem is resolved. 
Thanks for report.
