### ISSUE TITLE
OSX weird UI behavior

### ISSUE THREAD

**Issue by iongion** [tomoki1207/vscode-pdfviewer#7]
For a brief moment, when I click on the pdf, I first see an attempt of VS Code to display the bytes as text:

![image](https://cloud.githubusercontent.com/assets/867609/22127959/99a204fa-de9e-11e6-9b61-adb154d65e5c.png)

The it switches to the proper PDF viewer

![image](https://cloud.githubusercontent.com/assets/867609/22127994/c34d4710-de9e-11e6-8e1d-9ab5ca3a6918.png)

Can the first thing be prevented and just load the proper PDF viewer by default, avoiding memory spikes in the text editor ?

**Comment by tomoki1207** [comment]
@iongion 
The VSCode open PDF file as TextDocument by default as you know. And this extension reopen it as proper PDF via [onDidOpenTextDocument](https://code.visualstudio.com/Docs/extensionAPI/vscode-api) event and then close a initial tab.
So, I think it is difficult what avoid shown binary text until implement event like "onWillOpenTextDocument".

Instead, you can show PDF directly using right click on explorer and choose "View PDF" since 0.2.0.
That might be a little troublesome, could you try it?
