### ISSUE TITLE
macOS (only?): 20px padding between the sidebar and pdf area

### ISSUE THREAD

**Issue by yay** [tomoki1207/vscode-pdfviewer#8]
VS Code 1.10.1
vscode-pdf 0.2.0

![screen shot 2017-03-06 at 17 58 18](https://cloud.githubusercontent.com/assets/1799756/23620345/d99e9606-0296-11e7-84de-bf858d427da6.png)

**Comment by tomoki1207** [comment]
@yay Thank you for report.
This padding is prepared by VSCode, not set by our extension.
Other extensions with preview feature (like built-in markdown) also have this padding, but it is not noticeable because background-color depends on VSCode color theme.
So, it might be nice to be able to change PDF style rather than expand PDF area.

**Comment by yay** [comment]
I see. Changing the theme is probably too much work for too little benefit (the current look is already good), it's a pity the padding can't be removed. But no worries, this was my minor nit-pick, the extension is great as it is.
